# Generated by Django 5.1.2 on 2024-10-12 13:12

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='duration',
            field=models.PositiveIntegerField(default='60'),
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre.models.movie_image_file_path),
        ),
    ]
