# Generated by Django 5.1.2 on 2024-10-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_play_duration_play_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
    ]
